### ISSUE TITLE
[MFC] Error: getaddrinfo ENOTFOUND crashes streamdvr

### ISSUE THREAD

**Issue by kuchenstrudel** [jrudess/streamdvr#14]
I got this error which crashed streamdvr
> Error:
 getaddrinfo ENOTFOUND xchat85.myfreecams.com xchat85.myfreecams.com:8100
    at errnoException (dns.js:55:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)

**Comment by kuchenstrudel** [comment]
Got something similar today.
> Error: connect ECONNREFUSED 207.229.75.34:8100
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1207:14)

This crashed streamdvr.

**Comment by jrudess** [comment]
I have upgraded master branch to MFCAuto 5.1.0 which has improvements to resolve network connections killing the script.   This new version requires NodeJS >= 9.4.0.    If you have access to this version of NodeJS, hopefully this will resolve the issue.

**Comment by jrudess** [comment]
Resolved in v0.8.0
