### ISSUE TITLE
Error: Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by NeonStepZ** [jrudess/streamdvr#155]
Sorry for bothering, I'm pretty new to this stuff and have no clue how to fix this error. 

> Error: Cannot find module 'fs/promises'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/mnt/c/Users/NeonS/streamdvr-0.14.2/lib/core/postprocess.js:8:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)``

**Comment by jrudess** [comment]
What version of node are you using?

**Comment by NeonStepZ** [comment]
I am using v14.17.6

**Comment by jrudess** [comment]
After cloning the repo did you also run `npm install`?

**Comment by NeonStepZ** [comment]
Yes I did.

**Comment by jrudess** [comment]
I'm using nodejs 16.9.1 here.   Can you try editing lib/core/postprocess.js and make the following change.

At line 8, change:
`const fsp = require("fs/promises");`
To:
`const fsp = require("fs").promises`

It might still fail, but I'm looking to see if the stacktrace changse and the following line doesn't show up anymore:
```
at Object. (/mnt/c/Users/NeonS/streamdvr-0.14.2/lib/core/postprocess.js:8:13)
```

**Comment by NeonStepZ** [comment]
It's in a different directory this time but yea still same error I think. 


`internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'fs/promises'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/mnt/d/streamdvr/lib/core/postprocess.js:8:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)``

**Comment by jrudess** [comment]
At the moment, I don't have any other suggestions to try other than switching from the LTS version of node (14.7.6) to the latest version (16.9.1).

**Comment by NeonStepZ** [comment]
No problem thanks for trying!

**Comment by jrudess** [comment]
If you don't mind, can you send me the linux distribution and version you're using (as long as it's not windows + WSL)?  I can install that distro in a VM and see if I can replicate the failure.  That'll make it easier for me to fiddle around to find a solution.

**Comment by NeonStepZ** [comment]
I'm using ubuntu.

**Comment by NeonStepZ** [comment]
Sorry it's windows + wsl.

**Comment by jrudess** [comment]
When you type "uname -r" in a shell, what do you get?  I can probably still try to install that same version of Ubuntu in a VM and see if it reproduces the problem.

**Comment by jrudess** [comment]
Or if there is no 'uname' command, paste the contents of `cat /etc/os-release`

**Comment by NeonStepZ** [comment]
I got "4.4.0-19041-Microsoft"

**Comment by jrudess** [comment]
Ah, bummer.  Looks like I won't be able to help debug further as I have no access to any Windows machines.
