### ISSUE TITLE
error recording not found in capturing directory cannot convert to ts

### ISSUE THREAD

**Issue by challi1337** [jrudess/streamdvr#165]
I had to update pandalive plugin so streamlink would work again, but now I ran into this error. I saw this error came up before and got fixed. running streamdvr in alpine docker image with streamlink 6.9.0 for m3u8 and recording

full error:

not found in capturing directory, cannot convert to ts                    
    at Streamdvr.log (/app/lib/core/dvr.js:162:21)                               
    at Streamdvr.msg (/app/lib/core/dvr.js:174:18)                               
    at Streamdvr.print (/app/lib/core/dvr.js:198:18)                             
    at Basic.print (/app/lib/core/site.js:537:18)                                
    at Basic.endCapture (/app/lib/core/site.js:514:22)                           
    at async /app/lib/core/site.js:486:17

**Comment by jrudess** [comment]
Are you using ffmpeg or streamlink to capture?  Can you share your config.yml file for pandalive?

**Comment by challi1337** [comment]
My config for pandalive:

> enable:
>   daemon: false
> recording:
>   autoConvertType: ts
>   captureDirectory: /capturing
>   completeDirectory: /captured
>   postprocess: ""
>   dateFormat: "YYYYMMDD_HHmmss"
>   fileNameFormat: "%n_%s_%d"
>   includeSiteInDir: false
>   streamerSubdir: true
>   siteSubdir: true
>   keepTsFile: false
>   minSize: 0
>   maxSize: 0
> postprocess: ""
> log:
>   enable: true
>   append: false
> tui:
>   enable: false
>   allowUnicode: true
> colors:
>   name: magenta
>   state: yellow
>   offline: blue
>   prompt: blue
>   file: green
>   time: grey
>   site: green
>   cmd: grey
>   debug: yellow
>   error: red
> proxy:
>   enable: false
>   server: socks5://188.74.169.96:5393
> debug:
>   log: true
>   recorder: true
>   errortrace: true

I'm using streamlink for the m3u8 and capturing. I tried ffmpeg after I saw your comment which resulted in the same error

**Comment by jrudess** [comment]
In addition to the config.yml, can you post your pandalive.yml file as well?   I set one up but I just get "403 forbidden" errors when the recorder tries to access the m3u8 stream.   Do you use an account+authentication?  If so, I probably can't help debug since I don't have an account.

**Comment by challi1337** [comment]
for sure here my pandalive.yml

> name: PANDALIVE
> plugin: ./lib/plugins/basic
> siteUrl: https://www.pandalive.co.kr/live/play/
> urlback: ''
> enable: true
> m3u8fetch: scripts/custom/m3u8_streamlink.sh
> recorder: scripts/record_ffmpeg.sh
> scanInterval: 240
> batchSize: 1
> streamers:
>   - - fnsk0061
>     - unpaused
>   - - anystar00
>     - unpaused
>   - - aa000sss
>     - unpaused
>   - - '58588253'
>     - unpaused
>   - - nemu00
>     - unpaused
>   - - imanatural
>     - unpaused
>   - - dmsdms1247
>     - unpaused

I give the cookie in the script, but I'd rather not post it openly here since they are pretty fast to flag and ban when they see too much activity. You could contact me on discord (sebthefirst) or tell me a way to get in contact with you.
