### ISSUE TITLE
client crashes on disconnect 

### ISSUE THREAD

**Issue by kuchenstrudel** [jrudess/streamdvr#17]
Internet was gone for ~1 minute and the client crashed with the following

> Error:
 Cannot call TxCmd on a disconnected client
    at Client.TxCmd (/home/foo/streamdvr/node_modules/MFCAuto/lib/Client.js:873:19)
    at Client.login (/home/foo/streamdvr/node_modules/MFCAuto/lib/Client.js:1562:18)
    at Socket._client.net.connect (/home/foo/streamdvr/node_modules/MFCAuto/lib/Client.js:1249:42)
    at Object.onceWrapper (events.js:219:13)
    at Socket.emit (events.js:132:15)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1176:10)

**Comment by jrudess** [comment]
Can you confirm if you are have the latest commit 04738066e01e9882a8fb8151e9c7de22d95b19ab ?

Also, how is mfcWebSocket set in mfc.yml?

**Comment by kuchenstrudel** [comment]
Yes and yes (set to `true`).

**Comment by kuchenstrudel** [comment]
Never mind, I was missing the latest commit. Will test and report back if the issue persist.

**Comment by jrudess** [comment]
Thanks, I was hoping that would be the case.

I have only a few days of testing truly using websockets, but so far things are looking pretty good.   Been powering down router, and disconnecting cable modem and  haven't induced any script killing disconnects yet.

**Comment by kuchenstrudel** [comment]
New disconnect, new error.

>Error: WebSocket is not open: readyState 0 (CONNECTING)
    at WebSocket.send (/home/foo/streamdvr/node_modules/ws/lib/websocket.js:367:19)
    at WebSocket._client.on (/home/foo/streamdvr/node_modules/MFCAuto/lib/Client.js:1291:46)
    at WebSocket.emit (events.js:180:13)
    at WebSocket.setSocket (/home/foo/streamdvr/node_modules/ws/lib/websocket.js:166:10)
    at ClientRequest._req.on (/home/foo/streamdvr/node_modules/ws/lib/websocket.js:703:10)
    at ClientRequest.emit (events.js:180:13)
    at Socket.socketOnData (_http_client.js:476:11)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:581:20)

**Comment by ZombieAlex** [comment]
Can you run this command in your application folder and share the output? `npm ls --depth 0` The line numbers in your call stack don't entirely align with what I'd expect you to have.

Also what OS and Node versions are you using? Try upgrading both of them, if possible. And then blowing away your entire node_modules folder and re-running `npm install` at the root.

Something may be off with your setup because both of your stacks should be impossible.
 - WebSocket.emit is the [ws module](https://github.com/websockets/ws) emitting an event explicitly saying the socket is open.
 - The next frame up is my handler for socket open and the first thing I do is write to it...
 - Which then throws saying the socket is in "connecting" state rather than open.

No part of that makes sense. [This is the websocket.js code](https://github.com/websockets/ws/blob/a04d9855a5a3d9bab62f9d22bcf5d1ee8185726b/lib/websocket.js) that you should be on. It wouldn't emit an open event unless it had set its state to open. Then even if you somehow lost connection in the nanoseconds between WS emitting "open" and the .send call, it would not have had any opportunity to set its state back to "connecting" to cause that error text.

The first stack is similarly baffling.

**Comment by ZombieAlex** [comment]
And also try to update to MFCAuto v5.2.1. I did make a subtle change in this area that might help.

**Comment by kuchenstrudel** [comment]
`npm ls --depth 0`:
> mfc-node@0.1.0 /home/foo/streamdvr
+-- blessed@0.1.81 (github:chjj/blessed#eab243fc7ad27f1d2932db6134f7382825ee3488)
+-- bluebird@3.5.1
+-- colors@1.2.1
+-- js-yaml@3.10.0
+-- MFCAuto@5.2.0 (github:ZombieAlex/MFCAuto#19668d0cd0a3c5da690778c65fe13eafea3863a9)
+-- mkdirp@0.5.1
+-- moment@2.21.0
+-- mv@2.1.1
+-- node-fetch@2.0.0
+-- string@3.3.3
`-- underscore@1.8.3

OS: [Arch Linux ARM](https://archlinuxarm.org/)
NodeJS: v9.9.0 (nodejs 9.9.0-2)

**Comment by kuchenstrudel** [comment]
Currently upgrading to `nodejs-9.11.1-1` and `npm-5.8.0-1`, will purge the node_modules dir and re-run `npm install`.

**Comment by ZombieAlex** [comment]
Thanks. I was hoping that output would capture your "ws" module version, but it did not. It's ok.

The more I think about it, the more I believe I've fixed this in v5.2.1 of MFCAuto. You can edit your local package.json to update that reference, then `npm install` again to pick it up.

**Comment by ZombieAlex** [comment]
That new stack is almost equally troubling. The socket was open, and put itself into closing state apparently without ever emitting an error or close event.

I also just saw you have another open issue here dealing with a login error, which would also be my code. These are all things that really should not happen, at least not with the frequency that you seem to be seeing them. I wouldn't rule out an OS or hardware level issue.

**Comment by kuchenstrudel** [comment]
The hardware is a Raspberry Pi 1 Model B, so it's not the fastest.

**Comment by kuchenstrudel** [comment]
At least the client didn't crash. :+1: 

>[20180413_054317] MFC      [ERROR] Error: WebSocket is not open: readyState 0 (CONNECTING)
[20180413_054317] MFC      [ERROR] Error: WebSocket is not open: readyState 0 (CONNECTING)                                 
[20180413_054318] MFC      [ERROR] Error: WebSocket is not open: readyState 0 (CONNECTING)                                 
[20180413_054320] MFC      [ERROR] Error: WebSocket is not open: readyState 0 (CONNECTING)                                 
[20180413_054321] MFC      [ERROR] Error: WebSocket is not open: readyState 0 (CONNECTING)
[20180413_054321] MFC      [ERROR] Error: WebSocket is not open: readyState 0 (CONNECTING)                                 
[20180413_054322] MFC      [ERROR] Error: WebSocket is not open: readyState 0 (CONNECTING)
[20180413_054322] MFC      [ERROR] Error: WebSocket is not open: readyState 0 (CONNECTING)     
[20180413_054324] MFC      [ERROR] Error: WebSocket is not open: readyState 0 (CONNECTING)                                 
[20180413_054824] MFC      [ERROR] Error: WebSocket is not open: readyState 0 (CONNECTING)                                 
[20180413_054825] MFC      [ERROR] Error: WebSocket is not open: readyState 0 (CONNECTING)                                 
[20180413_054825] MFC      [ERROR] Error: WebSocket is not open: readyState 0 (CONNECTING)                                 
[20180413_054826] MFC      [ERROR] Error: WebSocket is not open: readyState 0 (CONNECTING)
[20180413_054827] MFC      [ERROR] Error: WebSocket is not open: readyState 0 (CONNECTING)                                 
[20180413_054827] MFC      [ERROR] Error: WebSocket is not open: readyState 0 (CONNECTING)
[20180413_054828] MFC      [ERROR] Error: WebSocket is not open: readyState 0 (CONNECTING)                                 
[20180413_054829] MFC      [ERROR] Error: WebSocket is not open: readyState 0 (CONNECTING)
[20180413_054829] MFC      [ERROR] Error: WebSocket is not open: readyState 0 (CONNECTING)                                 
[20180413_054830] MFC      [ERROR] Error: WebSocket is not open: readyState 0 (CONNECTING)

**Comment by ZombieAlex** [comment]
@jrudess My best guess on this most recent one is that you've called `queryUser` on a client that had been connected but is currently disconnected and trying to reconnect.

This possibility is the reason I added the [`state`](https://github.com/ZombieAlex/MFCAuto/tree/master/src/main#clientstate) and [`ensureConnected`](https://github.com/ZombieAlex/MFCAuto/tree/master/src/main#clientensureconnectedtimeout) properites to Client in v5.0.0. If `client.state === mfc.ClientState.ACTIVE` then the connection is live. So you could guard the call with that check, or if you want to do some operation the moment a connection is restored, do something like this...

```javascript
client.ensureConnected()
   .then(() => {
       //The connection should be open here
   });
```

I should probably detect this on my side and throw a more helpful error message.

**Comment by ZombieAlex** [comment]
I won't attempt to host it publicly anymore or be the primary install point. If other people want to fork it and host it, that's on them.

However, I will continue to develop it and if you (and I mean literally you, @jrudess, and not any random person who may read this in the future) want access to my changes send me an email.

**Comment by jrudess** [comment]
Going to close this older issue out.   If you run into any good new stack-traces with the latest and greatest, please open up a new one.
