### ISSUE TITLE
Error: Login failed

### ISSUE THREAD

**Issue by kuchenstrudel** [jrudess/streamdvr#24]
Got a new crash. Using current `master` branch with `mfcWebSocket: true`.

> Error: Login failed
    at Client._packetReceived (/home/foo/streamdvr/node_modules/MFCAuto/lib/Client.js:232:27)
    at Client._readWebSocketPacket (/home/foo/streamdvr/node_modules/MFCAuto/lib/Client.js:610:18)
    at Client._readWebSocketData (/home/foo/streamdvr/node_modules/MFCAuto/lib/Client.js:211:14)
    at WebSocket._client.on (/home/foo/streamdvr/node_modules/MFCAuto/lib/Client.js:1305:38)
    at WebSocket.emit (events.js:180:13)
    at Receiver._receiver.onmessage (/home/foo/streamdvr/node_modules/ws/lib/websocket.js:137:47)
    at Receiver.dataMessage (/home/foo/streamdvr/node_modules/ws/lib/receiver.js:409:14)
    at Receiver.getData (/home/foo/streamdvr/node_modules/ws/lib/receiver.js:347:12)
    at Receiver.startLoop (/home/foo/streamdvr/node_modules/ws/lib/receiver.js:143:16)
    at Receiver.add (/home/foo/streamdvr/node_modules/ws/lib/receiver.js:117:10)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:581:20)

**Comment by k3admm** [comment]
I got this error
`[06/08/2018 - 13:22:06] Connecting to MyFreeCams websocket server xchat119...
[06/08/2018 - 13:22:07] Login handshake completed. Logged in as 'Guest90690' with sessionId 02180963
[20180608_132210] MFC      [ERROR] TypeError: Cannot read property 'ACTIVE' of undefined`

**Comment by jrudess** [comment]
This link will only be valid for 2 days, so let me know if you don't get it in time.  Can you play around with a newerversion of MFCAuto and see how the fatal error solution looks now? 

 https://volafile.org/get/BOpmiprD2Nwyz/MFCAuto_v5.6.0.tar.gz

**Comment by kuchenstrudel** [comment]
I'm getting A LOT of ` MFC      [ERROR] Error: WebSocket is not open: readyState 2 (CLOSING)` with that version.
Dunno if that has something to do with me using an ARM CPU. 

I might also have installed that release wrong. :wink:

**Comment by jrudess** [comment]
Interesting, that's not one I've run into yet.  Does it kind of work and then you get those errors?  Or does it not even start up?

Seems unlikely to be related to ARM, except by way of a NodeJS bug.

**Comment by kuchenstrudel** [comment]
> Does it kind of work and then you get those errors?

Correct, it start's recording and then later you see those errors.
I assume once it does some kind of refresh?

**Comment by jrudess** [comment]
Seems like a new signature for when connection errors are happening.  So on each cycle it checks the online status, and if the socket got corrupt, then it'll trigger that error for each model most likely.

Does it happen forever after that, or does eventually mfcauto recover get a new socket connection, and recordings resume?

**Comment by kuchenstrudel** [comment]
Not sure, I'm currently using a non ARM machine and no errors yet.

**Comment by jrudess** [comment]
@kuchenstrudel new bug fix that can cause connection errors and crashes https://volafile.org/get/BSYCfdjz82GZI/MFCAuto_v5.6.1.tar.gaz

**Comment by kuchenstrudel** [comment]
Seem to work well.
