### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by longsack** [jrudess/streamdvr#29]
Some issues it seems with some recent take downs, do you plan to continue support?

During Install.....   I have MFCAuto.git intalled already.... so tried... to run.....
[ .................] \ loadIdealTree:loadAllDepsIntoIdealTree: sill install loadIdealTree
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/ZombieAlex/MFCAuto.git
npm ERR!
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-26T12_10_33_368Z-debug.log

Run: node streamdvr.js  Throws this error
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'bluebird'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/admin/web/capturebate.web-porn-network.com/public_html/recorders/streamdvr/streamdvr.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)

Perhaps because I was not able to continue the install.... any suggestions/ help?

Thanks

**Comment by jrudess** [comment]
See #26 

You can use the instructions there to get streamdvr up and running, but mfc will not function unless you have your own copy of MFCAuto.
