### ISSUE TITLE
ERR_CONSOLE_WRITABLE_STREAM('stdout');

### ISSUE THREAD

**Issue by longsack** [jrudess/streamdvr#40]
Any idea why it's throwing this error?

root@ns518041:/home/admin/web/public_html/recorders/streamdvr# dir
cb_updates.yml  config.yml  LICENSE.md       mfc.yml            mixer.yml     package.json       plugins    streamdvr.js   streamdvr.service   twitch.yml
cb.yml          core        mfc_updates.yml  mixer_updates.yml  node_modules  package-lock.json  README.md  streamdvr.log  twitch_updates.yml
root@ns518041:/home/admin/web/public_html/recorders/streamdvr# node streamdvr.js
console.js:39
    throw new ERR_CONSOLE_WRITABLE_STREAM('stdout');
    ^

TypeError [ERR_CONSOLE_WRITABLE_STREAM]: Console expects a writable stream instance for stdout
    at new Console (console.js:39:11)
    at createSites (/home/admin/web/public_html/recorders/streamdvr/streamdvr.js:38:18)
    at Object.<anonymous> (/home/admin/web/public_html/recorders/streamdvr/streamdvr.js:79:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
root@ns518041:/home/admin/web/public_html/recorders/streamdvr#

**Comment by jrudess** [comment]
My best guess is its being launched from a shell with no display and that's a use-case I have not tested before.

**Comment by jrudess** [comment]
It doesn't look like directory permission issue as I get an EACCES error in that case.   Can you provide OS and node version?

**Comment by Ptibouc77** [comment]
Same for me i can't use the latest version cause this happen every time (but old versions working well)

console.js:38
    throw new errors.TypeError('ERR_CONSOLE_WRITABLE_STREAM', 'stdout');
    ^

TypeError [ERR_CONSOLE_WRITABLE_STREAM]: Console expects a writable stream instance for stdout
    at new Console (console.js:38:11)
    at createSites (C:\Users\Desktop\Bouc\streamdvr-master\streamdvr.js:38:18)
    at Object.<anonymous> (C:\Users\Desktop\Bouc\streamdvr-master\streamdvr.js:100:1)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:660:3

My node version is v9.7.1 and i Use Windows 10 x64 (build 17134)

**Comment by longsack** [comment]
As soon as home I will provide the node version, I'm using Debian 8 OS..  Will get the Node version as soon as possible to you.

**Comment by longsack** [comment]
Part of the issue could be i'm on node 9.11.1 will update.

**Comment by longsack** [comment]
Ok, so ya, I updated node to 10.5 and I have no issues .... ready to close... anyone else having this issue check and make sure your nodejs version is 9.4.0 or better as required
