### ISSUE TITLE
Error With TUI: True  "TypeError: value.nm.padEnd is not a function"

### ISSUE THREAD

**Issue by longsack** [jrudess/streamdvr#73]
If I mark TUI as true in the config file it throws the following error:

TypeError: value.nm.padEnd is not a function
    at Tui.render (/var/www/clients/client1/web1/web/recorders/streamdvr/core/tui.js:264:56)
    at Tui.display (/var/www/clients/client1/web1/web/recorders/streamdvr/core/tui.js:303:14)
    at Tui.init (/var/www/clients/client1/web1/web/recorders/streamdvr/core/tui.js:202:18)
    at createSites (/var/www/clients/client1/web1/web/recorders/streamdvr/streamdvr.js:72:9)
    at Object.<anonymous> (/var/www/clients/client1/web1/web/recorders/streamdvr/streamdvr.js:75:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)

I'm sure I'm just missing something small, anyone else have this or know of a fix?

Thanks

**Comment by Asynchr0nous** [comment]
if it is the former then a simple update should fix the issue

**Comment by longsack** [comment]
Could never get this to work... so I got a different box, now have other issues, see "Fresh Install" issue... :)  Trying! :)

**Comment by lukiluki123** [comment]
Modify line 264 in tui.js to this and it will work:
const name  = colors.name(value.nm.toString().padEnd(22, " "));
